name: Bump Crossplane Formula

on:
  workflow_dispatch:
    inputs:
      new_version:
        description: 'New version (example: 1.14.0)'
        required: true

jobs:
  open-pr:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      - name: Bump crossplane formula versions
        id: bump_crossplane
        run: |
          bin/bump-formula-crossplane.sh -v ${{ github.event.inputs.new_version }}
          echo "crossplane_formula_file=$(bin/bump-formula-crossplane.sh -v ${{ github.event.inputs.new_version }} -f)" >> "$GITHUB_OUTPUT"
          echo "crossplane_formula_name=$(bin/bump-formula-crossplane.sh -v ${{ github.event.inputs.new_version }} -n)" >> "$GITHUB_OUTPUT"
      - name: Setup homebrew
        id: setup-homebrew
        uses: Homebrew/actions/setup-homebrew@9db18afa3016668c5f7e0b5d65c4eed7c1c0739e
      - name: Install the newly created formula
        run: brew install tampakrap/tap/${{ steps.bump_crossplane.outputs.crossplane_formula_name }}
      - name: Test the newly created formula
        run: brew test ${{ steps.bump_crossplane.outputs.crossplane_formula_name }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@38e0b6e68b4c852a5500a94740f0e535e0d7ba54  # v4.2.4
        with:
          commit-message: "feat(${{ steps.bump_crossplane.outputs.crossplane_formula_file }}): Bump to version `${{ github.event.inputs.new_version }}`"
          title: "feat(${{ steps.bump_crossplane.outputs.crossplane_formula_file }}): Bump to version `${{ github.event.inputs.new_version }}`"
          body: ""
          branch: "create-pull-request/${{ github.event.inputs.new_version }}"
