name: Install and Test Crossplane

on:
  pull_request:
    paths:
      - Formula/crossplane*.rb

jobs:
  install-test-crossplane:
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-15]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup homebrew
        id: setup-homebrew
        uses: Homebrew/actions/setup-homebrew@9db18afa3016668c5f7e0b5d65c4eed7c1c0739e
      - name: Get changed crossplane formulas
        id: changed-crossplane-formulas
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c  # v46.0.5
        with:
          files: "Formula/crossplane*.rb"
      - name: List all changed crossplane formulas
        id: list-changed-crossplane-formulas
        if: steps.changed-crossplane-formulas.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_CROSSPLANE_FORMULAS: ${{ steps.changed-crossplane-formulas.outputs.all_changed_files }}
        run: |
          for formula in ${ALL_CHANGED_CROSSPLANE_FORMULAS}; do
            echo "Formula $formula was changed"
            crossplane_formula_name=$(basename "$formula" ".rb")
            echo "crossplane_formula_name=$crossplane_formula_name" >> "$GITHUB_OUTPUT"
          done
      - name: Install the new crossplane formula version
        run: brew install tampakrap/tap/${{ steps.list-changed-crossplane-formulas.outputs.crossplane_formula_name }}
      - name: Cache Homebrew Bundler RubyGems
        id: cache-rubygems
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684  # v4.2.3
        with:
          path: ${{ steps.setup-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-brew-test-rubygems-${{ steps.setup-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-brew-test-rubygems-
      - name: Install Homebrew Bundler RubyGems
        if: steps.cache-rubygems.outputs.cache-hit != 'true'
        run: brew install-bundler-gems
      - name: Test the new crossplane formula version
        run: brew test ${{ steps.list-changed-crossplane-formulas.outputs.crossplane_formula_name }}
      - run: crossplane version --client
